# Server configuration
server:
  address: 0.0.0.0
  port: ${PORT:8080}
# Spring Config
spring:
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

# App Config
app:
  config:
    rsa-key:
      public-key: classpath:certs/public.pem
      private-key: classpath:certs/private.pem
    otp:
      size: 6
      ttl: 120s
    challenge:
      length: 32 #in bytes
      ttl: 60s
  amqp:
    publisher:
      notifications:
        otp:
          exchange: notifications.commands.v1.exchange
          routing-key: send.otp.email
