# Spring Config
spring:
  config:
    import: optional:file:.env
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  # DB Config
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT:5432}/${DB_SCHEMA:auth-service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    # Connection pool settings
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
  # JPA / Hibernate settings
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        '[show_sql]': false
        '[format_sql]': true
        '[globally_quoted_identifiers]': true
# App Config
app:
  config:
    rsa-key:
      public-key: ${RSA_PUBLIC_KEY}
      private-key: ${RSA_PRIVATE_KEY}
    otp:
      size: 6
      ttl: 120s
    challenge:
      length: 32 #in bytes
      ttl: 60s
    passkey:
      rp:
        rp-id: "bankapp.online"
        auth-mode: smartphone
      security:
        user-presence-required: true
        user-verification-required: true
  feature:
    verification:
      initiate:
        enabled: true
      complete:
        enabled: true
    authentication:
      initiate:
        enabled: true
      complete:
        enabled: false
    registration:
      enabled: false
  amqp:
    publisher:
      notifications:
        otp:
          exchange: notifications.commands.v1.exchange
          routing-key: send.otp.email