# Server configuration
server:
  address: 0.0.0.0
  port: ${PORT:8080}

# Spring Config
spring:
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
  # DB Config
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:auth-service}
    username: ${POSTGRES_USERNAME:dev}
    password: ${POSTGRES_PASSWORD:dev}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        '[globally_quoted_identifiers]': true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# App Config
app:
  cors:
    allowed-origins:
      - http://auth.localhost
      - ${CORS_ALLOWED_ORIGIN1}
      - ${CORS_ALLOWED_ORIGIN2}
    allowed-methods:
    allowed-headers:
    allow-credentials: true
    max-age: 3600
  config:
    passkey:
      rp:
        rp-id: ${PASSKEY_RPID:localhost} #set it in test & test-postgres properties, to avoid config conflicts with test setup
        auth-mode: ${AUTH_MODE:smartphone}
        origin: ${PASSKEY_ORIGIN:http://localhost}
      security:
        user-presence-required: ${UP_FLAG:true}
        user-verification-required: ${UV_FLAG:true}
    otp:
      size: 6
      ttl: 120s
    challenge:
      length: 32 #in bytes
      ttl: 60s
  feature:
    verification:
      initiate:
        enabled: true
      complete:
        enabled: true
    authentication:
      initiate:
        enabled: true
      complete:
        enabled: true
    registration:
      complete:
        enabled: true
  amqp:
    publisher:
      notifications:
        otp:
          exchange: notifications.commands.v1.exchange
          routing-key: send.otp.email

logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    bankapp: DEBUG
