spring:
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672

app:
  config:
    otp:
      size: 6
      ttl: 120s
  feature:
    verification:
      enabled: false
    registration:
      enabled: false
    authentication:
      enabled: false
  amqp:
    publisher:
      notifications:
        otp:
          exchange: notifications.commands.v1.exchange
          routing-key: send.otp.email