spring:
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379

app:
  config:
    otp:
      size: 6
      ttl: 120s
    challenge:
      length: 32 #in bytes
  feature:
    verification:
      initiate:
        enabled: true
      complete:
        enabled: false
    registration:
      enabled: false
    authentication:
      enabled: false
  amqp:
    publisher:
      notifications:
        otp:
          exchange: notifications.commands.v1.exchange
          routing-key: send.otp.email