# compose for testing purposes
# compose.yml

networks:
  bankapp-test:
    driver: bridge
services:
  postgres-db:
    image: postgres:16
    container_name: auth-dev-postgres-db
    environment:
      - POSTGRES_DB=auth-service
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
    networks:
      - bankapp-test
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: auth-dev-redis
    ports:
      - "6379:6379"
    networks:
      - bankapp-test
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: auth-dev-rabbitmq
    hostname: dev
    ports:
      - "5672:5672"
      - "127.0.0.1:15672:15672"
    networks:
      - bankapp-test
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres-data:
  redis-data:
  rabbitmq_data: