# compose for testing purposes
# compose.yml

networks:
  bankapp-test:
    external: true
  bankapp-auth:
    driver: bridge

services:
  postgres-db:
    image: postgres:16
    container_name: auth-dev-postgres-db
    ports:
      - "5432:5432"
    networks:
      - bankapp-test
    env_file:
      - ".env.docker"

  redis:
    image: redis:7-alpine
    container_name: auth-dev-redis
    ports:
      - "6379:6379"
    networks:
      - bankapp-test
    env_file:
      - ".env.docker"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "127.0.0.1:15672:15672"
    networks:
      - bankapp-test
    env_file:
      - ".env.docker"
